version: "3.8"
services:
    frontend:
        environment:
            APP_NAME: restaurant
            APP_ENV: production
            APP_KEY: base64:Nmg3Z3c0ODR5bDQ0OXZoNWR0ZXdldWVpdHNxM2RiMDI=
            APP_DEBUG: false
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        ports:
            - "8100:80"
        networks:
            - alegra-net
networks:
    alegra-net:
        driver: bridge
